FROM node:20-alpine

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copia os arquivos de gerenciamento de pacotes
COPY package*.json ./

# Instala todas as dependências (incluindo as de desenvolvimento, necessárias para o build)
RUN npm install

# Copia o restante do código da sua aplicação
COPY . .

# Executa o script de build do seu package.json
RUN npm run build